import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const dotemp8bit = localFont({
  src: './fonts/Dotemp-8bit.woff',
  variable: '--font-dotemp-bit',
  weight: '500',
});
const ppNeueMontrealBook = localFont({
  src: './fonts/ppneuemontreal-book.woff',
  variable: '--font-pp-book',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dotemp8bit.variable} ${ppNeueMontrealBook.variable} antialiased`}>{children}</body>
    </html>
  );
}
